AWSTemplateFormatVersion: '2010-09-09'
Description: >-
  This template creates Nginx App Protect Autoscale solution. The template uses
  nested templates for provisioning network, access, compute resources for hosting
  NAP Autoscale solution.
  **WARNING** This template creates AWS resources. 
  You will be billed for the AWS resources used
  if you create a stack from this template. QS(0027)
Conditions:
  az2: !Or
    - !Equals
      - !Ref numAzs
      - '2'
    - !Condition az3
  az3: !Or
    - !Equals
      - !Ref numAzs
      - '3'
    - !Condition az4
  az4: !Equals
    - !Ref numAzs
    - '4'  
Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
      - Label:
          default: Instance Configuration
        Parameters:
          - sshKey
          - instanceType
          - napScalingMaxSize
          - napScalingMinSize
      - Label:
          default: Network Configuration
        Parameters:
          - vpcCidr
          - subnetMask
          - numAzs
          - provisionPublicIp
      - Label:
          default: Resource Tags
        Parameters:
          - cost
          - environment
          - group
          - owner
          - uniqueString
      - Label:
          default: Modules folder
        Parameters:
          - s3ModulesBucketName
          - s3ModulesPath
    ParameterLabels:
      sshKey:
        default: SSH Key
      instanceType:
        default: Instance Type
      napScalingMaxSize:
        default: Maximum number of NAP instances
      napScalingMinSize:
        default: Minimum number of NAP instance
      vpcCidr:
        default: VPC CIDR
      subnetMask:
        default: Subnet Mask
      numAzs:
        default: Number of Availability Zones
      provisionPublicIp:
        default: Provision Public IP Addresses
      cost:
        default: Cost
      environment:
        default: Environment
      group:
        default: Group
      owner:
        default: Owner
      uniqueString:
        default: Unique String
      s3ModulesBucketName:
        default: S3 Modules Bucket Name
      s3ModulesPath:
        default: S3 Modules Path
  Version: 1.0.0
Mappings:
  amiRegionMap:
    ap-east-1:
      UBUNTU1804DEV: ami-02cbed36dd3616a84
    ap-northeast-1:
      UBUNTU1804DEV: ami-0ec278cf695de326c
    ap-northeast-2:
      UBUNTU1804DEV: ami-0a32800963fa115bb
    ap-northeast-3:
      UBUNTU1804DEV: ami-0491c330c1b3e44c9
    ap-south-1:
      UBUNTU1804DEV: ami-0139359797b6e3cbb
    ap-southeast-1:
      UBUNTU1804DEV: ami-09f7be100fa49db35
    ap-southeast-2:
      UBUNTU1804DEV: ami-0def18da152bd01ef
    ca-central-1:
      UBUNTU1804DEV: ami-0c6eed9d2e970780a
    eu-central-1:
      UBUNTU1804DEV: ami-0e1d0cb0c1de0aaed
    eu-west-1:
      UBUNTU1804DEV: ami-0c3748a507e3e6af6
    eu-west-2:
      UBUNTU1804DEV: ami-0525f8e90a9ea0713
    eu-west-3:
      UBUNTU1804DEV: ami-0c60f7962a6f712ed
    eu-north-1:
      UBUNTU1804DEV: ami-09ff9e4279f34d409
    sa-east-1:
      UBUNTU1804DEV: ami-00eef560ede5acabe
    us-east-1:
      UBUNTU1804DEV: ami-0f58d396d72867d57
    us-east-2:
      UBUNTU1804DEV: ami-0b912107985ac7145
    us-west-1:
      UBUNTU1804DEV: ami-02f5b222247cd8471
    us-west-2:
      UBUNTU1804DEV: ami-0ead4783e8d139c88  
Outputs:
  externalDnsName:
    Value: !GetAtt Dag.Outputs.externalElasticLoadBalancerDnsName
  externalHttpsUrl:
    Value: !Sub 'http://${Dag.Outputs.externalElasticLoadBalancerDnsName}'
Parameters:
  numAzs:
    Default: 2
    Description: Number of Availability Zones to use in the VPC. Region must support
      number of availability  zones entered. Min 1 Max 4.
    MaxValue: 4
    MinValue: 1
    Type: Number
  provisionPublicIp:
    AllowedValues:
      - 'true'
      - 'false'
    Default: 'true'
    Description: Whether or not to provision Public IP Addresses for the Internal Network
      Interfaces.
    Type: String
  subnetMask:
    ConstraintDescription: 'Subnet mask must be in value of 16-28. Total number of
      subnets created from VPC must be greater than or equal to number of regions
      multiplied by number of subnets. Example: 4 AZ with 8 subnets requires VPC supernetting
      support 32 subnets.'
    Default: 24
    Description: 'Mask for subnets. Valid values include 16-28. Note supernetting
      of VPC occurs based on mask provided; therefore, number of networks must be
      >= to the number of subnets created. Mask for subnets. Valid values include
      16-28.'
    MaxValue: 28
    MinValue: 16
    Type: Number
  vpcCidr:
    AllowedPattern: '^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$'
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.0.0/16
    Description: CIDR block for the VPC.
    Type: String
  napScalingMaxSize:
    ConstraintDescription: Must be a number between 2-100
    Default: 50
    Description: Maximum number of NAP instances (2-100) that can be created in
      the Auto Scale Group.
    MaxValue: 100
    MinValue: 2
    Type: Number
  napScalingMinSize:
    ConstraintDescription: Must be a number between 1-99
    Default: 2
    Description: Minimum number of NAP instances (1-99) you want available in the
      Auto Scale Group.
    MaxValue: 99
    MinValue: 1
    Type: Number
  s3ModulesBucketName:
    AllowedPattern: '^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$'
    ConstraintDescription: 'S3 bucket name can include numbers, lowercase letters,
      uppercase letters, and hyphens (-). It cannot start or end with a hyphen (-).'
    Description: 'REQUIRED - S3 bucket name for the modules. S3 bucket name can include
      numbers, lowercase letters, uppercase letters, and hyphens (-). It cannot start
      or end with a hyphen (-).'
    Default: aws-waf-solution-template
    Type: String
  s3ModulesPath:
    AllowedPattern: ^.*[a-zA-Z]+/$
    ConstraintDescription: key prefix can include numbers, lowercase letters, uppercase
      letters, hyphens (-), and forward slash (/).
    Default: release/latest/modules/
    Description: The path in the S3Bucket where the modules folder is located. Can
      include numbers, lowercase letters, uppercase letters, hyphens (-), and forward
      slash (/).
    Type: String
  sshKey:
    Description: REQUIRED - Supply the public key that will be used for SSH authentication
      to the virtual machines.
    Type: 'AWS::EC2::KeyPair::KeyName'
  instanceType:
    Description: Amazon EC2 instance type for the NGINX instances
    Type: String
    Default: t3.small
    AllowedValues:
      - t2.nano
      - t2.micro
      - t2.small
      - t3.nano
      - t3.micro
      - t3.small
  cost:
    Default: f5cost
    Description: Cost Center Tag.
    Type: String
  environment:
    Default: f5env
    Description: Environment Tag.
    Type: String
  group:
    Default: f5group
    Description: Group Tag.
    Type: String
  owner:
    Default: f5owner
    Description: Owner Tag.
    Type: String
  uniqueString:
    ConstraintDescription: 'Must Contain between 1 and 12 alphanumeric characters
      with first character as a letter.'
    AllowedPattern: ^[a-zA-Z][a-zA-Z0-9]{1,11}$
    Description: Unique String used when creating object names or Tags.
    Type: String
    Default: myUniqStr
Resources:
  Pipeline:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://${s3ModulesBucketName}.s3.amazonaws.com/${s3ModulesPath}pipeline/pipeline.yaml'
      Parameters:
        cost: !Ref cost
        environment: !Ref environment
        group: !Ref group
        owner: !Ref owner
        instanceIAMRole: !GetAtt NAPAutoScale.Outputs.napIAMRole
        targetGroupName: !GetAtt Dag.Outputs.externalTargetGroupHttpName
        initialRepositoryS3Bucket: !Ref s3ModulesBucketName
        initialRepositoryS3Key: !Sub '${s3ModulesPath}autoscale/nginx-app-protect-ubuntu-18.04/initial_repo.zip'
        autoScalingGroupList: !Join
          - ','
          - - !GetAtt NAPAutoScale.Outputs.autoScalingGroup
        uniqueString: !Ref uniqueString
  Telemetry:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://${s3ModulesBucketName}.s3.amazonaws.com/${s3ModulesPath}telemetry/nap-autoscale-telemetry.yaml'
      Parameters:
        instanceIAMRole: !GetAtt NAPAutoScale.Outputs.napIAMRole
        logGroupName: !Sub '${uniqueString}-log-group'
        autoScalingGroup: !GetAtt NAPAutoScale.Outputs.autoScalingGroup
        loadBalancerFullName: !GetAtt Dag.Outputs.externalElasticLoadBalancerFullName
        targetGroupFullName: !GetAtt Dag.Outputs.externalTargetGroupHttpFullName
        uniqueString: !Ref uniqueString
  Dag:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://${s3ModulesBucketName}.s3.amazonaws.com/${s3ModulesPath}dag/dag.yaml'
      Parameters:
        cost: !Ref cost
        environment: !Ref environment
        group: !Ref group
        owner: !Ref owner
        externalSubnets: !Join
          - ','
          - - !Select
              - '0'
              - !Split
                - ','
                - !GetAtt Network.Outputs.subnetsA
            - !If 
              - az2
              - !Select
                - '0'
                - !Split
                  - ','
                  - !GetAtt Network.Outputs.subnetsB 
              - !Ref AWS::NoValue
            - !If 
              - az3
              - !Select
                - '0'
                - !Split
                  - ','
                  - !GetAtt Network.Outputs.subnetsC
              - !Ref AWS::NoValue
            - !If 
              - az4
              - !Select
                - '0'
                - !Split
                  - ','
                  - !GetAtt Network.Outputs.subnetsD
              - !Ref AWS::NoValue
        numberPublicExternalIpAddresses: 0
        uniqueString: !Ref uniqueString
        vpc: !GetAtt Network.Outputs.vpcId
        vpcCidr: !Ref vpcCidr
  Network:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://${s3ModulesBucketName}.s3.amazonaws.com/${s3ModulesPath}network/network.yaml'
      Parameters:
        cost: !Ref cost
        environment: !Ref environment
        group: !Ref group
        owner: !Ref owner
        numAzs: !Ref numAzs
        numSubnets: 2
        setPublicSubnet1: !Ref provisionPublicIp
        subnetMask: !Ref subnetMask
        uniqueString: !Ref uniqueString
        vpcCidr: !Ref vpcCidr
        vpcTenancy: default
  NAPAutoScale:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://${s3ModulesBucketName}.s3.amazonaws.com/${s3ModulesPath}autoscale/nginx-app-protect-ubuntu-18.04/nap-autoscale.yaml'
      Parameters:
        cost: !Ref cost
        environment: !Ref environment
        group: !Ref group
        owner: !Ref owner
        externalTargetGroupHttp: !GetAtt Dag.Outputs.externalTargetGroupHttp
        imageId: !FindInMap
        - amiRegionMap
        - !Ref AWS::Region
        - UBUNTU1804DEV
        instanceType: !Ref instanceType
        provisionPublicIp: !Ref provisionPublicIp
        scalingMaxSize: !Ref napScalingMaxSize
        scalingMinSize: !Ref napScalingMinSize
        sshKey: !Ref sshKey
        subnets: !Join
          - ','
          - - !Select
              - '1'
              - !Split
                - ','
                - !GetAtt Network.Outputs.subnetsA
            - !If 
              - az2
              - !Select
                - '1'
                - !Split
                  - ','
                  - !GetAtt Network.Outputs.subnetsB 
              - !Ref AWS::NoValue
            - !If 
              - az3
              - !Select
                - '1'
                - !Split
                  - ','
                  - !GetAtt Network.Outputs.subnetsC
              - !Ref AWS::NoValue
            - !If 
              - az4
              - !Select
                - '1'
                - !Split
                  - ','
                  - !GetAtt Network.Outputs.subnetsD
              - !Ref AWS::NoValue
        napExternalSecurityGroup: !GetAtt Dag.Outputs.externalSecurityGroup
        logGroupName: !Sub '${uniqueString}-log-group'
        uniqueString: !Ref uniqueString